on:
   push:
     branches:
       - main
   schedule:
    - cron: 30 00 * * 0,1,2,3,4,5,6 # runs ar 12:30AM UTC == 6:00AM IST everyday.
jobs:
   build-and-scrape-site:
     name: Deploy and scrape static site
     runs-on: ubuntu-latest

     env:
       APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
       API_KEY: ${{ secrets.API_KEY }}

     steps:
       - name: Checkout
         uses: actions/checkout@v2

       - uses: actions/setup-node@v2
         with:
           node-version: '14'

       - name: Install dep's
         run: |
           yarn install && yarn build
       - name: Create .nojekyll file for GitHub Pages
         run: |
           touch build/.nojekyll
       - name: Deploy to GitHub Pages
         if: success()
         uses: crazy-max/ghaction-github-pages@v2
         with:
           target_branch: gh-pages
           build_dir: ./build
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}