name: Run Algolia Doc-Search

on:
   push:
     branches:
       - main
   schedule:
    - cron: 30 00 * * 0,1,2,3,4,5,6 # runs ar 12:30AM UTC == 6:00AM IST everyday.

jobs:
  docsearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          echo "APPLICATION_ID=$APPLICATION_ID" >> .env
          echo "API_KEY=$API_KEY" >> .env
          chmod +x ./bin/crawl.sh
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_DOCSEARCH_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_DOCSEARCH_API_KEY }}
      - name: Run docsearch
        continue-on-error: true
        run: |
          ./bin/crawl.sh

